### ISSUE TITLE
Crash on CM13

### ISSUE THREAD

**Issue by jpotier** [krt16s/ffupdater#2]
For me, app crashes upon clicking on "I'm feeling lucky".

It might come from the fact I'm using a nightly build of CM13, however `ffupdater` is the only app that has this kind of crashy behaviour.

Some details on my configuration:
```
Build number: cm_peregrine-userdebug 6.0.1 MMB29U
CyanogenMod version: 13.0-20160210-NIGHTLY-peregrine
Android version: 6.0.1
```

Some trace around the time I start the app and push the "I'm feeling lucky" button:
```
--------- beginning of system
…
02-11 10:59:06.125   747  1726 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=de.marmaro.krt.ffupdater/.MainActivity} from uid 10080 on display 0
02-11 10:59:06.190   747  1153 I ActivityManager: Start proc 32116:de.marmaro.krt.ffupdater/u0a97 for activity de.marmaro.krt.ffupdater/.MainActivity
02-11 10:59:06.288 32116 32116 W System  : ClassLoader referenced unknown path: /data/app/de.marmaro.krt.ffupdater-1/lib/arm
02-11 10:59:06.361 32116 32116 I MainActivity: Firefox 44.0 (2015396233) is installed.
02-11 10:59:06.361 32116 32116 I MainActivity: UpdateUri: https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi
02-11 10:59:06.373 32116 32140 D OpenGLRenderer: Use EGL_SWAP_BEHAVIOR_PRESERVED: true
02-11 10:59:06.427 32116 32140 I Adreno-EGL: <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 10/09/15, 6cbbf7d, I3193f6e94a
02-11 10:59:06.429 32116 32140 I OpenGLRenderer: Initialized EGL, version 1.4
02-11 10:59:06.605   747   767 I ActivityManager: Displayed de.marmaro.krt.ffupdater/.MainActivity: +445ms
02-11 10:59:08.379   747  3485 D NetlinkSocketObserver: NeighborEvent{elapsedMs=33614843, 192.168.1.1, [028EF24BF013], RTM_NEWNEIGH, NUD_PROBE}
02-11 10:59:08.739   232   413 I ThermalEngine: Sensor:batt_therm:25700 mC
02-11 10:59:09.253   222   998 D audio_hw_primary: out_standby: enter: stream (0xb7b050d8) usecase(1: low-latency-playback)
02-11 10:59:09.329   222   998 D hardware_info: hw_info_append_hw_type : device_name = speaker-lite
02-11 10:59:10.485   747  1041 D WifiStateMachine: starting scan for "\_o<"-WPA_PSK with 2462
02-11 10:59:14.165 19529 19539 I art     : Background sticky concurrent mark sweep GC freed 117521(5MB) AllocSpace objects, 0(0B) LOS objects, 38% free, 8MB/13MB, paused 476us total 148.945ms
02-11 10:59:18.745   232   413 I ThermalEngine: Sensor:batt_therm:25700 mC
02-11 10:59:21.420   747  3485 D NetlinkSocketObserver: NeighborEvent{elapsedMs=33627884, 192.168.1.1, [028EF24BF013], RTM_NEWNEIGH, NUD_STALE}
02-11 10:59:23.071   222   998 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
02-11 10:59:23.081   222   998 D audio_hw_primary: start_output_stream: enter: stream(0xb7b050d8)usecase(1: low-latency-playback) devices(0x2)
02-11 10:59:23.081   222   998 D audio_hw_primary: start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
02-11 10:59:23.082   222   998 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
02-11 10:59:23.082   222   998 W msm8974_platform: Codec backend bitwidth 16, samplerate 48000
02-11 10:59:23.082   222   998 D hardware_info: hw_info_append_hw_type : device_name = speaker-lite
02-11 10:59:23.082   222   998 I msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 14, path =  0
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> send_adm_topology
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> send_audtable
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> send_audvoltable
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
02-11 10:59:23.082   222   998 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
02-11 10:59:23.091   222   998 D audio_hw_primary: select_devices: done
02-11 10:59:23.168  1112 23768 W DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/temp.apk
02-11 10:59:23.171  1112 23768 E DatabaseUtils: Writing exception to parcel
02-11 10:59:23.171  1112 23768 E DatabaseUtils: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/temp.apk: Neither user 10097 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at android.app.ContextImpl.enforce(ContextImpl.java:1450)
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1482)
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at com.android.providers.downloads.DownloadProvider.checkFileUriDestination(DownloadProvider.java:724)
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at com.android.providers.downloads.DownloadProvider.insert(DownloadProvider.java:558)
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at android.content.ContentProvider$Transport.insert(ContentProvider.java:263)
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:163)
02-11 10:59:23.171  1112 23768 E DatabaseUtils: 	at android.os.Binder.execTransact(Binder.java:453)
02-11 10:59:23.172 32116 32116 D AndroidRuntime: Shutting down VM
02-11 10:59:23.172 32116 32116 E AndroidRuntime: FATAL EXCEPTION: main
02-11 10:59:23.172 32116 32116 E AndroidRuntime: Process: de.marmaro.krt.ffupdater, PID: 32116
02-11 10:59:23.172 32116 32116 E AndroidRuntime: java.lang.SecurityException: No permission to write to /storage/emulated/0/Download/temp.apk: Neither user 10097 nor current process has android.permission.WRITE_EXTERNAL_STORAGE.
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1620)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.content.ContentResolver.insert(ContentResolver.java:1236)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.app.DownloadManager.enqueue(DownloadManager.java:954)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at de.marmaro.krt.ffupdater.MainActivity.downloadAndInstall(MainActivity.java:66)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at de.marmaro.krt.ffupdater.MainActivity$2.onClick(MainActivity.java:196)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.view.View.performClick(View.java:5204)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.view.View$PerformClick.run(View.java:21156)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5466)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
02-11 10:59:23.172 32116 32116 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
02-11 10:59:23.174   747  1611 W ActivityManager:   Force finishing activity de.marmaro.krt.ffupdater/.MainActivity
02-11 10:59:23.254   747 27746 I OpenGLRenderer: Initialized EGL, version 1.4
02-11 10:59:23.297   747   757 I art     : Background partial concurrent mark sweep GC freed 65058(4MB) AllocSpace objects, 22(440KB) LOS objects, 33% free, 17MB/26MB, paused 2.661ms total 100.864ms
02-11 10:59:23.705   747   762 W ActivityManager: Activity pause timeout for ActivityRecord{3a4125c u0 de.marmaro.krt.ffupdater/.MainActivity t183 f}
02-11 10:59:26.292   222   998 D audio_hw_primary: out_standby: enter: stream (0xb7b050d8) usecase(1: low-latency-playback)
02-11 10:59:26.371   222   998 D hardware_info: hw_info_append_hw_type : device_name = speaker-lite
02-11 10:59:26.810   222   998 D audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
02-11 10:59:26.813 32116 32116 I Process : Sending signal. PID: 32116 SIG: 9
02-11 10:59:26.821   222   998 D audio_hw_primary: start_output_stream: enter: stream(0xb7b050d8)usecase(1: low-latency-playback) devices(0x2)
02-11 10:59:26.821   222   998 D audio_hw_primary: start_output_stream: enter: usecase(1: low-latency-playback) devices(0x2)
02-11 10:59:26.821   222   998 D audio_hw_primary: select_devices: out_snd_device(2: speaker) in_snd_device(0: )
02-11 10:59:26.821   222   998 W msm8974_platform: Codec backend bitwidth 16, samplerate 48000
02-11 10:59:26.821   222   998 D hardware_info: hw_info_append_hw_type : device_name = speaker-lite
02-11 10:59:26.821   222   998 I msm8974_platform: platform_send_audio_calibration: sending audio calibration for snd_device(2) acdb_id(14)
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> send_audio_cal, acdb_id = 14, path =  0
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> send_adm_topology
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> send_audtable
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_CAL
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> send_audvoltable
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
02-11 10:59:26.821   222   998 D ACDB-LOADER: ACDB -> AUDIO_SET_AFE_CAL
02-11 10:59:26.826   222   998 D audio_hw_primary: select_devices: done
02-11 10:59:26.855   747   767 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
02-11 10:59:26.888   747  1726 D GraphicsStats: Buffer count: 14
02-11 10:59:26.889   747  1726 I WindowState: WIN DEATH: Window{48d61ea u0 de.marmaro.krt.ffupdater/de.marmaro.krt.ffupdater.MainActivity}
02-11 10:59:26.903   222   998 D AudioFlinger: mixer(0xb4177008) throttle end: throttle time(10)
02-11 10:59:26.940   747   759 I ActivityManager: Process de.marmaro.krt.ffupdater (pid 32116) has died
02-11 10:59:28.750   232   413 I ThermalEngine: Sensor:batt_therm:25700 mC
02-11 10:59:29.249   747  3485 D NetlinkSocketObserver: NeighborEvent{elapsedMs=33635713, 192.168.1.1, [028EF24BF013], RTM_NEWNEIGH, NUD_PROBE}
02-11 10:59:30.033   222   998 D audio_hw_primary: out_standby: enter: stream (0xb7b050d8) usecase(1: low-latency-playback)
02-11 10:59:30.111   222   998 D hardware_info: hw_info_append_hw_type : device_name = speaker-lite
```

**Comment by jpotier** [comment]
Aaaaand, I solved it by explicitly ticking the "storage access" button in application details. It would seem that `ffupdater` does not ask for writing permission upon installation.

Might I suggest it should be looked into? : 3

**Comment by krt16s** [comment]
This is a change in Android6 / CM13, and it's already on my todo list (https://github.com/krt16s/ffupdater/blob/master/TODO). As with all others things I want to do, it's just a matter of finding the time for it.

Btw: Android 5 and below work fine.

**Comment by krt16s** [comment]
704df5b82ad3a5b29ec4841f03d848784bb2d5a5 should work around this by lowering the target version. Permission will be granted on installation for now... I really should take the time to clean the mess this app is, but I just hope Mozilla is non-playstore-updates on their end sooner or later...

Report back when this does not solve the problem for you.

**Comment by krt16s** [comment]
45.0b shouldn't crash anymore, but it doesnt get the correct current version...sigh..
